language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
services:
- postgresql
script: make test-all
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: alviner
  password:
    secure: vYaR6UaruDaYsIECMipA24D8vc3ukjo98NLCu4JY4mfVfBceoWXVfDufoTzRIMdvNUUgBKhJ9m0jKFCOb1CA/oi4QZYYvvH0NygT1t7SAmLpDgODZlwaUuDkiVk+nR4NHPp8Z3AswDusE/UhsHiOJYvudo4qUfqYs9TjmatOIMHoFPEC5BJWgXLJDuvUaLLozWunBCxUr/TAhN7gxPO6UWz+klxIfzaPGomNUqIHS8Lsd45KKK1n2P4lLX149PLU4HnhWg8NVVK423YmW+8iVfIjQ1cscGwJPUa2MStz4Cxn92ozfl/XTu3nNFuCFNFyXbvFUWMSv7Q5cRGyGCyT9w7eLu7fse2xtoMUyZWJDsBrsT4JTiXCTrLKOHgN2m8X3TLX8gUiMIVGgxN1Ec5CGrjcGPKxjtU2lkY7iDRB+el9UlAmSvFg52GA6Mxp9/oqaQqogiecXjC9+JgggFpWpKPPIEfjwcNZWF/XJNf5zvldG163LsNsgMmkUP2V/lTfYcrk3ElA7GSfi0hMO6NC6QRtuPzpzIB0nkl/hDqWlVMbmoZG1u9Hh2OMEQzEDX07OPJkuw9DsybXF8vTPn2UrvcKRFi8R7NFEBRv/dAy12m+GCaKPhIHxBPPMgh5uHKGcpW3l4Yk7yFnPpvcZXob8K84gl8rV+HroCYY2K0p8lk=
  on:
    tags: true
    repo: Alviner/async_lock
    python: 3.8
