language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
services:
- postgresql
script: make test-all
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: alviner
  password:
    secure: hf4fupzcI7W0urqI4tWLjLnD6zT7mKYcU957bDEzX5hqVxk6wUWVXrhap/EUHCOwpKIHAUEtd5g63aa1ev5RWv4qeSKnlrVqRyve1wei/crsTEvsSjUwZ62PzI7ctIsrZZsZFxjcbpH4L2BEiJ7LqQ4uQun9dX6dS/SS8MELkKlv4qnAlgezju9ar7RYHJJRK7rkK7aT7y0/6kninqrZH6kuW7g1DQiHKlnzjl6YNt5PSfRc8FpVoUbrdb5okrVnQpRzxCTiIweRE1ZPAttGLXXb2FQWzGMB5CFDNNiRVyaBBMze0Va8de8k32iRmF9zjJmoN9Pp8SiI+dgxeyD7hD0HrTnwusVlb9snxebCBEFzaiIyRlfO/aiB58x/+lwUFs/+RQu+74E+Ii6dubaBATR1BbAuqX3h0AOqzIkPOE7xWp9Za2oLnrt4vG4rsLoQ2OpZZE5UQx7eeFKbJwEgrTfp+DaoHZWGYmMS0N3L/ZD1sRCRNBozQgZX547QSS7TKgO530jZvN0Cby+a+4Xd8MgFJqmq7QgTze/7BrFxhvcWpOgqBQ29RE9F/Cj64LOw17oWIKm4Gg9H9ygUVo9JiRo9MxJEBHy9iwmG9ORZgu52RGhgR/3LJbs9QNAVhDUj2V6s1enZbQN8DJxQAxjTUMsqcXGGrd8jRGWCQ8eQIQQ=
  on:
    tags: true
    repo: Alviner/async_lock
    python: 3.8
