language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: alviner
  password:
    secure: cZbOTasVzRKAnhsn9/vw1E1VCcG6XcWKO9oxuoHNtQ9+74b2CRp4eYTD4ADkHurTpoaDf/6Zwzr7CCtWVvluD9FNfApEUiQ2M+sDXY3yccbHWlJkFMzGjOaE7M/NP0NDXT0gCsYnKBk6eOGY+o1Imqr8KW7OFKfi7R8BsDA1RH+F2rKhSmz6bya2vWR+x4ZCCmRVbgKB8bt3HUUzsZVn83CuG5NG9WlLo8JmZytoFPqeh7NwvaXZ0VRhKVN83rgyjauMFiO9ga9fItwbXwOnCmsO3u6Ukj6QFPt0UY2DUPJbeSzkeYJ9bixexV1Te8gkLEaoVIMVPpAkI8Sd985TWyn9hhBd9V0xMAvxW3HwdREwajhdvhNP5tmtP+8q1qZQgmNHzzP/qJWlZy9+iCXtIuuTB7wlGIs0CNtbYuPLu+I/XdvHeFBx5S5sNA1Ct/TjpL833qBl7GkqNuStPTl9BvYjiEP66DV5CTHcc5WEWHmMwPnRXb9lbDg2PlmAQ5fVJhDMt44BOmEZqvAyURQA6ixBJE6qWg8qqDxptGzbg3YiHFld7LYMgzJa058v4VicarWDs55ZOifv6mSFR4tTwjKDhYayu+jQ+IbxRglHcbbCc4TUqEB49BfuKvpexhtVv4SVNX6rWnyXu+TSzmHZopc6crOGeCRV0fNlbG/Fjco=
  on:
    tags: true
    repo: alviner/async_lock
    python: 3.8
