version: '3.4'

services:
  postgresql:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: pguser
      POSTGRES_USER: pguser
      POSTGRES_DB: pgdb
    ports:
      - '127.0.0.1:5432:5432'
